### ISSUE TITLE
Error fetching user stats

### ISSUE THREAD

**Issue by AbdBarho** [LAION-AI/Open-Assistant#1156]
I wanted to add user stats to the account page, and faced this error `KeyError('streak_days')`

<details>
<summary> Logs </summary>

```py
2023-02-05 07:39:48.938 | ERROR    | main:unhandled_exception_handler:53 - GET http://localhost:8080/api/v1/users/3cfd3dd9-e408-4ba5-89c9-cb887de66bf3/stats failed [UNHANDLED]: KeyError('streak_days')
Traceback (most recent call last):

  File "/usr/local/bin/gunicorn", line 8, in <module>
    sys.exit(run())
    │   │    └ <function run at 0x7f27958c28c0>
    │   └ <built-in function exit>
    └ <module 'sys' (built-in)>
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 67, in run
    WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
    └ <class 'gunicorn.app.wsgiapp.WSGIApplication'>
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/base.py", line 231, in run
    super().run()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/base.py", line 72, in run
    Arbiter(self).run()
    │       └ <gunicorn.app.wsgiapp.WSGIApplication object at 0x7f27958a0610>
    └ <class 'gunicorn.arbiter.Arbiter'>
  File "/usr/local/lib/python3.10/site-packages/gunicorn/arbiter.py", line 202, in run
    self.manage_workers()
    │    └ <function Arbiter.manage_workers at 0x7f2794fe2440>
    └ <gunicorn.arbiter.Arbiter object at 0x7f27958a06d0>
  File "/usr/local/lib/python3.10/site-packages/gunicorn/arbiter.py", line 551, in manage_workers
    self.spawn_workers()
    │    └ <function Arbiter.spawn_workers at 0x7f2794fe2560>
    └ <gunicorn.arbiter.Arbiter object at 0x7f27958a06d0>
  File "/usr/local/lib/python3.10/site-packages/gunicorn/arbiter.py", line 622, in spawn_workers
    self.spawn_worker()
    │    └ <function Arbiter.spawn_worker at 0x7f2794fe24d0>
    └ <gunicorn.arbiter.Arbiter object at 0x7f27958a06d0>
  File "/usr/local/lib/python3.10/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
    │      └ <function UvicornWorker.init_process at 0x7f27944bd630>
    └ <uvicorn.workers.UvicornWorker object at 0x7f2794804c70>
  File "/usr/local/lib/python3.10/site-packages/uvicorn/workers.py", line 66, in init_process
    super(UvicornWorker, self).init_process()
          │              └ <uvicorn.workers.UvicornWorker object at 0x7f2794804c70>
          └ <class 'uvicorn.workers.UvicornWorker'>
  File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/base.py", line 142, in init_process
    self.run()
    │    └ <function UvicornWorker.run at 0x7f27944bd870>
    └ <uvicorn.workers.UvicornWorker object at 0x7f2794804c70>
  File "/usr/local/lib/python3.10/site-packages/uvicorn/workers.py", line 98, in run
    return asyncio.run(self._serve())
           │       │   │    └ <function UvicornWorker._serve at 0x7f27944bd7e0>
           │       │   └ <uvicorn.workers.UvicornWorker object at 0x7f2794804c70>
           │       └ <function run at 0x7f27949c0d30>
           └ <module 'asyncio' from '/usr/local/lib/python3.10/asyncio/__init__.py'>
  File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
           │    │                  └ <coroutine object UvicornWorker._serve at 0x7f277a1155b0>
           │    └ <method 'run_until_complete' of 'uvloop.loop.Loop' objects>
           └ <uvloop.Loop running=True closed=False debug=False>
  File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 419, in run_asgi   
    result = await app(  # type: ignore[func-returns-value]
                   └ <uvicorn.middleware.proxy_headers.ProxyHeadersMiddleware object at 0x7f277a013d00>
  File "/usr/local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
                 │    │   │      │        └ <bound method RequestResponseCycle.send of <uvicorn.protocols.http.httptools_impl.RequestResponseCycle object at 0x7f27759499...
                 │    │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.httptools_impl.RequestResponseCycle object at 0x7f27759...
                 │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('172.19.0.7', 8080), 'c...
                 │    └ <fastapi.applications.FastAPI object at 0x7f2794861480>
                 └ <uvicorn.middleware.proxy_headers.ProxyHeadersMiddleware object at 0x7f277a013d00>
  File "/usr/local/lib/python3.10/site-packages/fastapi/applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
                           │      │        └ <bound method RequestResponseCycle.send of <uvicorn.protocols.http.httptools_impl.RequestResponseCycle object at 0x7f27759499...
                           │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.httptools_impl.RequestResponseCycle object at 0x7f27759...
                           └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('172.19.0.7', 8080), 'c...
  File "/usr/local/lib/python3.10/site-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
          │    │                │      │        └ <bound method RequestResponseCycle.send of <uvicorn.protocols.http.httptools_impl.RequestResponseCycle object at 0x7f27759499...
          │    │                │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.httptools_impl.RequestResponseCycle object at 0x7f27759...
          │    │                └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('172.19.0.7', 8080), 'c...
          │    └ <starlette.middleware.errors.ServerErrorMiddleware object at 0x7f277a2d7550>
          └ <fastapi.applications.FastAPI object at 0x7f2794861480>
> File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
          │    │   │      │        └ <function ServerErrorMiddleware.__call__.<locals>._send at 0x7f2779f1f370>    
          │    │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.httptools_impl.RequestResponseCycle object at 0x7f27759...
          │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('172.19.0.7', 8080), 'c...
          │    └ <starlette.middleware.exceptions.ExceptionMiddleware object at 0x7f277a2d74f0>
          └ <starlette.middleware.errors.ServerErrorMiddleware object at 0x7f277a2d7550>
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
          │    │   │      │        └ <function ExceptionMiddleware.__call__.<locals>.sender at 0x7f2779f1f2e0>     
          │    │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.httptools_impl.RequestResponseCycle object at 0x7f27759...
          │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('172.19.0.7', 8080), 'c...
          │    └ <fastapi.middleware.asyncexitstack.AsyncExitStackMiddleware object at 0x7f277a2d73a0>
          └ <starlette.middleware.exceptions.ExceptionMiddleware object at 0x7f277a2d74f0>
  File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__        
    raise e
  File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__        
    await self.app(scope, receive, send)
          │    │   │      │        └ <function ExceptionMiddleware.__call__.<locals>.sender at 0x7f2779f1f2e0>     
          │    │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.httptools_impl.RequestResponseCycle object at 0x7f27759...
          │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('172.19.0.7', 8080), 'c...
          │    └ <fastapi.routing.APIRouter object at 0x7f27945321a0>
          └ <fastapi.middleware.asyncexitstack.AsyncExitStackMiddleware object at 0x7f277a2d73a0>
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 706, in __call__
    await route.handle(scope, receive, send)
          │     │      │      │        └ <function ExceptionMiddleware.__call__.<locals>.sender at 0x7f2779f1f2e0> 
          │     │      │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.httptools_impl.RequestResponseCycle object at 0x7f27759...
          │     │      └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('172.19.0.7', 8080), 'c...
          │     └ <function Route.handle at 0x7f27920e11b0>
          └ APIRoute(path='/api/v1/users/{user_id}/stats', name='query_user_stats', methods=['GET'])
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
          │    │   │      │        └ <function ExceptionMiddleware.__call__.<locals>.sender at 0x7f2779f1f2e0>     
          │    │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.httptools_impl.RequestResponseCycle object at 0x7f27759...
          │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('172.19.0.7', 8080), 'c...
          │    └ <function request_response.<locals>.app at 0x7f277a13fc70>
          └ APIRoute(path='/api/v1/users/{user_id}/stats', name='query_user_stats', methods=['GET'])
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
                     │    └ <starlette.requests.Request object at 0x7f277594a530>
                     └ <function get_request_handler.<locals>.app at 0x7f277a13fbe0>
  File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 235, in app
    raw_response = await run_endpoint_function(
                         └ <function run_endpoint_function at 0x7f27922b3d90>
  File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 163, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
                 │                 │         │       └ {'api_client': ApiClient(api_key='1234', admin_email=None, trusted=True, frontend_type='web', id=UUID('6be50461-09a3-400c-bda...
                 │                 │         └ <function query_user_stats at 0x7f277a6ae3b0>
                 │                 └ <fastapi.dependencies.models.Dependant object at 0x7f277a0cbd60>
                 └ <function run_in_threadpool at 0x7f2792eb0af0>
  File "/usr/local/lib/python3.10/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
                 │     │         │        │      └ ()
                 │     │         │        └ functools.partial(<function query_user_stats at 0x7f277a6ae3b0>, api_client=ApiClient(api_key='1234', admin_email=None, trust...
                 │     │         └ <function run_sync at 0x7f27947f60e0>
                 │     └ <module 'anyio.to_thread' from '/usr/local/lib/python3.10/site-packages/anyio/to_thread.py'>
                 └ <module 'anyio' from '/usr/local/lib/python3.10/site-packages/anyio/__init__.py'>
  File "/usr/local/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
                 └ <function get_asynclib at 0x7f27947f5a20>
  File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
                 └ <Future finished exception=KeyError('streak_days')>
  File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
             │       │   │      └ (<class 'KeyError'>, KeyError('streak_days'), None)
             │       │   └ <bound method _GeneratorContextManager.__exit__ of <contextlib._GeneratorContextManager 
object at 0x7f2775948670>>
             │       └ <method 'run' of '_contextvars.Context' objects>
             └ <_contextvars.Context object at 0x7f2779c68280>

  File "/app/oasst_backend/api/v1/users.py", line 300, in query_user_stats
    return usr.get_user_stats_all_time_frames(user_id=user_id)
           │   │                                      └ UUID('3cfd3dd9-e408-4ba5-89c9-cb887de66bf3')
           │   └ <function UserStatsRepository.get_user_stats_all_time_frames at 0x7f277a7be680>
           └ <oasst_backend.user_stats_repository.UserStatsRepository object at 0x7f2775949a20>

  File "/app/oasst_backend/user_stats_repository.py", line 172, in get_user_stats_all_time_frames
    stats_by_timeframe = {tf.value: _create_user_score(r, user_id) for tf in UserStatsTimeFrame}
                                    │                  │  │                  └ <enum 'UserStatsTimeFrame'>
                                    │                  │  └ UUID('3cfd3dd9-e408-4ba5-89c9-cb887de66bf3')
                                    │                  └ (UUID('3cfd3dd9-e408-4ba5-89c9-cb887de66bf3'), 'dev1', 'local', 'dev1', None)
                                    └ <function _create_user_score at 0x7f277a7be320>

  File "/app/oasst_backend/user_stats_repository.py", line 172, in <dictcomp>
    stats_by_timeframe = {tf.value: _create_user_score(r, user_id) for tf in UserStatsTimeFrame}
                          │  │      │                  │  │            │     └ <enum 'UserStatsTimeFrame'>
                          │  │      │                  │  │            └ <UserStatsTimeFrame.day: 'day'>
                          │  │      │                  │  └ UUID('3cfd3dd9-e408-4ba5-89c9-cb887de66bf3')
                          │  │      │                  └ (UUID('3cfd3dd9-e408-4ba5-89c9-cb887de66bf3'), 'dev1', 'local', 'dev1', None)
                          │  │      └ <function _create_user_score at 0x7f277a7be320>
                          │  └ <types.DynamicClassAttribute object at 0x7f2795a59330>
                          └ <UserStatsTimeFrame.day: 'day'>

  File "/app/oasst_backend/user_stats_repository.py", line 55, in _create_user_score
    d[k] = r[k]
    │ │    │ └ 'streak_days'
    │ │    └ (UUID('3cfd3dd9-e408-4ba5-89c9-cb887de66bf3'), 'dev1', 'local', 'dev1', None)
    │ └ 'streak_days'
    └ {'modified_date': datetime.datetime(2023, 2, 5, 7, 39, 48, 937391, tzinfo=datetime.timezone.utc), 'user_id': 
UUID('3cfd3dd9-e...

  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/result.py", line 72, in _key_fallback
    util.raise_(KeyError(key), replace_context=err)
    │    │               │                     └ None
    │    │               └ 'streak_days'
    │    └ <function raise_ at 0x7f279414e4d0>
    └ <module 'sqlalchemy.util' from '/usr/local/lib/python3.10/site-packages/sqlalchemy/util/__init__.py'>        
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
    raise exception

KeyError: 'streak_days'
```

</detials>

**Comment by Lyrialtus** [comment]
Well, if we look at the `user_stats_repository.py` file, we'll see that the `qry` in `get_user_stats_all_time_frames` wasn't updated.

Compare
https://github.com/LAION-AI/Open-Assistant/blob/063157355ce5d42d662f027a587363c8d8c72fe9/backend/oasst_backend/user_stats_repository.py#L73
with the changed
https://github.com/LAION-AI/Open-Assistant/blob/063157355ce5d42d662f027a587363c8d8c72fe9/backend/oasst_backend/user_stats_repository.py#L48-L56
So, at least at the surface level of analysis, these `qry`s should share the same `query()` base, synced with what is going on in `_create_user_score`, I think.

**Comment by olliestanley** [comment]
@AbdBarho can you check whether #1177 solves your problem?
