### ISSUE TITLE
Usage of backend/import.py

### ISSUE THREAD

**Issue by nero19960329** [LAION-AI/Open-Assistant#1928]
**Environment**
- version: 1f23005960d98fd0a00fe64d606a5b11da9093aa

**Step**
- `sudo docker-compose --profile backend-dev --profile frontend-dev up`
- `sudo docker exec -it <backend_container_id> bash`
- `python export.py --export-file data.json --state all`
  - Export all conversation tree data from my own environment. It was successful.
- `python import.py data.json`
  - It failed.

Content of `export.json`:

```
{"message_tree_id": "cff4c829-c788-44a1-a20d-7451af932f9d", "tree_state": "growing", "prompt": {"message_id": "cff4c829-c788-44a1-a20d-7451af932f9d", "text": "\u4eca\u5929\u4f60\u5403\u4e86\u4ec0\u4e48\uff1f", "role": "prompter", "lang": "zh", "review_count": 3, "review_result": true, "deleted": false, "synthetic": false, "emojis": {"_skip_reply": 1}, "replies": []}}
{"message_tree_id": "9c0d0de4-09fe-4616-9bee-9b24a48b720b", "tree_state": "growing", "prompt": {"message_id": "9c0d0de4-09fe-4616-9bee-9b24a48b720b", "text": "\u4eca\u5929\u5929\u6c14\u5982\u4f55\uff1f", "role": "prompter", "lang": "zh", "review_count": 3, "review_result": true, "deleted": false, "synthetic": false, "replies": []}}
{"message_tree_id": "fa25ae70-85af-4c85-bb55-f05c576a585d", "tree_state": "growing", "prompt": {"message_id": "fa25ae70-85af-4c85-bb55-f05c576a585d", "text": "\u4f60\u6700\u559c\u6b22\u7684\u7f16\u7a0b\u8bed\u8a00\u662f\u4ec0\u4e48\uff1f", "role": "prompter", "lang": "zh", "review_count": 3, "review_result": true, "deleted": false, "synthetic": false, "emojis": {"_skip_reply": 1}, "replies": []}}
{"message_tree_id": "370e1d44-c660-4e42-8ee4-e05e21f35eb5", "tree_state": "growing", "prompt": {"message_id": "370e1d44-c660-4e42-8ee4-e05e21f35eb5", "text": "\u4f60\u597d\uff01", "role": "prompter", "lang": "zh", "review_count": 3, "review_result": true, "deleted": false, "synthetic": false, "replies": []}}
{"message_tree_id": "0b371130-c46c-48cd-bba7-110f0d742a50", "tree_state": "growing", "prompt": {"message_id": "0b371130-c46c-48cd-bba7-110f0d742a50", "text": "\u4eca\u5929\u8fc7\u7684\u5982\u4f55\uff1f", "role": "prompter", "lang": "zh", "review_count": 3, "review_result": true, "deleted": false, "synthetic": false, "replies": []}}
{"message_tree_id": "70ab6939-5786-4efc-a89e-0ae87534c34c", "tree_state": "growing", "prompt": {"message_id": "70ab6939-5786-4efc-a89e-0ae87534c34c", "text": "\u767e\u5ea6\u767e\u79d1\u548c\u7ef4\u57fa\u767e\u79d1\u54ea\u4e2a\u4fe1\u606f\u66f4\u5168\u9762\uff1f", "role": "prompter", "lang": "zh", "review_count": 3, "review_result": true, "deleted": false, "synthetic": false, "replies": [{"message_id": "008a0b74-8fe0-4344-acd4-6dc6eae9765b", "parent_id": "70ab6939-5786-4efc-a89e-0ae87534c34c", "text": "\u6211\u89c9\u5f97\u662f\u7ef4\u57fa\u767e\u79d1\u3002", "role": "assistant", "lang": "zh", "review_count": 3, "review_result": true, "deleted": false, "synthetic": false, "replies": [{"message_id": "0db4af85-bcaf-46c7-be69-43e51b573eef", "parent_id": "008a0b74-8fe0-4344-acd4-6dc6eae9765b", "text": "\u4e3a\u4ec0\u4e48\u5462\uff1f\u53ef\u4ee5\u8bf4\u4e00\u4e0b\u7406\u7531\u5417\uff1f", "role": "prompter", "lang": "zh", "review_count": 3, "review_result": true, "deleted": false, "synthetic": false, "replies": [{"message_id": "012aa371-bac7-4c0f-b5a4-4dac9661267d", "parent_id": "0db4af85-bcaf-46c7-be69-43e51b573eef", "text": "\u6211\u8ba4\u4e3a\u7ef4\u57fa\u767e\u79d1\u4e0a\u7684\u5185\u5bb9\u66f4\u52a0\u771f\u5b9e\u53ef\u89c2\uff0c\u4f46\u767e\u5ea6\u767e\u79d1\u7684\u5185\u5bb9\u771f\u5b9e\u6027\u5f88\u591a\u90fd\u6709\u5f85\u8003\u8bc1\u3002", "role": "assistant", "lang": "zh", "review_count": 3, "review_result": true, "deleted": false, "synthetic": false, "emojis": {"+1": 1}, "replies": []}, {"message_id": "e5f624d3-6175-4623-b63a-2e12e534cd18", "parent_id": "0db4af85-bcaf-46c7-be69-43e51b573eef", "text": "\u7ef4\u57fa\u767e\u79d1\u6c47\u96c6\u4e86\u5168\u4e16\u754c\u7f51\u7edc\u7684\u4fe1\u606f\uff0c\u800c\u767e\u5ea6\u767e\u79d1\u53ea\u6709\u4e2d\u56fd\u56fd\u5185\u7684\u4fe1\u606f\u3002", "role": "assistant", "lang": "zh", "review_count": 3, "review_result": true, "deleted": false, "synthetic": false, "replies": []}]}]}, {"message_id": "85a55df0-cc84-4caf-831d-1106135cb227", "parent_id": "70ab6939-5786-4efc-a89e-0ae87534c34c", "text": "\u4e2d\u6587\u6211\u89c9\u5f97\u662f\u767e\u5ea6\u767e\u79d1\uff0c\u82f1\u6587\u6211\u89c9\u5f97\u662f\u7ef4\u57fa\u767e\u79d1\u3002", "role": "assistant", "lang": "zh", "review_count": 3, "review_result": true, "deleted": false, "synthetic": false, "replies": [{"message_id": "8f31e8ee-df91-4989-954f-72e3442c603b", "parent_id": "85a55df0-cc84-4caf-831d-1106135cb227", "text": "\u4f60\u786e\u5b9a\uff1f\u6211\u89c9\u5f97\u767e\u5ea6\u767e\u79d1\u7684\u4fe1\u606f\u8d28\u91cf\u5f88\u4f4e\u3002", "role": "prompter", "lang": "zh", "review_count": 3, "review_result": true, "deleted": false, "synthetic": false, "replies": []}]}]}}
{"message_tree_id": "d01214d3-a895-4207-b3e7-4d73167c2fd3", "tree_state": "growing", "prompt": {"message_id": "d01214d3-a895-4207-b3e7-4d73167c2fd3", "text": "\u4f60\u89c9\u5f97\u82f9\u679c\u624b\u673a\u597d\u8fd8\u662f\u534e\u4e3a\u624b\u673a\u597d\uff1f", "role": "prompter", "lang": "zh", "review_count": 3, "review_result": true, "deleted": false, "synthetic": false, "replies": [{"message_id": "71cd1091-1955-4185-9ada-261907681df5", "parent_id": "d01214d3-a895-4207-b3e7-4d73167c2fd3", "text": "\u4e24\u8005\u5404\u6709\u5404\u7684\u597d\u5904\uff0c\u4e0d\u80fd\u7528\u4e00\u53e5\u8bdd\u505a\u5b9a\u8bba\u3002", "role": "assistant", "lang": "zh", "review_count": 3, "review_result": true, "deleted": false, "synthetic": false, "replies": [{"message_id": "d2a2579b-caf0-4fc9-a540-47019d924136", "parent_id": "71cd1091-1955-4185-9ada-261907681df5", "text": "\u4ece\u7528\u6237\u4f53\u9a8c\u4e0a\u6765\u8bf4\uff0c\u82f9\u679c\u624b\u673a\u597d\u8fd8\u662f\u534e\u4e3a\u624b\u673a\u597d\uff1f", "role": "prompter", "lang": "zh", "review_count": 3, "review_result": true, "deleted": false, "synthetic": false, "emojis": {"+1": 1, "_skip_reply": 1}, "replies": []}]}]}}
{"message_tree_id": "4e10240d-22d3-4f66-ade8-30cb9538772a", "tree_state": "growing", "prompt": {"message_id": "4e10240d-22d3-4f66-ade8-30cb9538772a", "text": "\u897f\u7ea2\u67ff\u7092\u9e21\u86cb\u600e\u4e48\u505a\uff1f", "role": "prompter", "lang": "zh", "review_count": 3, "review_result": true, "deleted": false, "synthetic": false, "replies": []}}
{"message_tree_id": "90b88dae-b3f4-4636-accb-00c8648cecde", "tree_state": "growing", "prompt": {"message_id": "90b88dae-b3f4-4636-accb-00c8648cecde", "text": "\u6a31\u6843\u548c\u8f66\u5398\u5b50\u6709\u4ec0\u4e48\u533a\u522b\uff1f", "role": "prompter", "lang": "zh", "review_count": 3, "review_result": true, "deleted": false, "synthetic": false, "emojis": {"_skip_reply": 1}, "replies": []}}
{"message_tree_id": "eb7d4f1f-3c68-4694-bf55-6596053e4518", "tree_state": "growing", "prompt": {"message_id": "eb7d4f1f-3c68-4694-bf55-6596053e4518", "text": "\u4f60\u597d\uff0c\u6211\u4eec\u53ef\u4ee5\u4e0b\u4e09\u5b50\u68cb\u5417\uff1f", "role": "prompter", "lang": "zh", "review_count": 3, "review_result": true, "deleted": false, "synthetic": false, "replies": []}}
```

Error message:
```
2023-03-02 09:00:50.185 | DEBUG    | oasst_backend.prompt_repository:__init__:85 - PromptRepository(api_client_id=bd8fde8b-1d8e-4e9a-9966-e96d000f8363, self.user_id=None)
2023-03-02 09:00:50.201 | INFO     | __main__:import_tx:127 - imported tree: cff4c829-c788-44a1-a20d-7451af932f9d, mts.state='backlog_ranking', mts.active=False, root_msg.children_count=0
2023-03-02 09:00:50.204 | INFO     | oasst_backend.utils.database_utils:wrapped_f:200 - (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)
(psycopg2.errors.NotNullViolation) null value in column "lang" of relation "message_tree_state" violates not-null constraint
DETAIL:  Failing row contains (cff4c829-c788-44a1-a20d-7451af932f9d, 0, 0, 0, backlog_ranking, f, export.json, null, null).

[SQL: INSERT INTO message_tree_state (message_tree_id, origin, won_prompt_lottery_date, lang, goal_tree_size, max_depth, max_children_count, state, active) VALUES (%(message_tree_id)s, %(origin)s, %(won_prompt_lottery_date)s, %(lang)s, %(goal_tree_size)s, %(max_depth)s, %(max_children_count)s, %(state)s, %(active)s)]
[parameters: {'message_tree_id': UUID('cff4c829-c788-44a1-a20d-7451af932f9d'), 'origin': 'export.json', 'won_prompt_lottery_date': None, 'lang': None, 'goal_tree_size': 0, 'max_depth': 0, 'max_children_count': 0, 'state': 'backlog_ranking', 'active': False}]
(Background on this error at: https://sqlalche.me/e/14/gkpj)
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.NotNullViolation: null value in column "lang" of relation "message_tree_state" violates not-null constraint
DETAIL:  Failing row contains (cff4c829-c788-44a1-a20d-7451af932f9d, 0, 0, 0, backlog_ranking, f, export.json, null, null).


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/import.py", line 188, in <module>
    main()
  File "/app/import.py", line 175, in main
    num_imported = import_file(
  File "/app/import.py", line 138, in import_file
    return import_tx()
  File "/app/oasst_backend/utils/database_utils.py", line 201, in wrapped_f
    raise e
  File "/app/oasst_backend/utils/database_utils.py", line 164, in wrapped_f
    result = f(session, *args, **kwargs)
  File "/app/import.py", line 120, in import_tx
    existing_mts = importer.fetch_message_tree_state(tree.message_tree_id)
  File "/app/import.py", line 48, in fetch_message_tree_state
    return self.db.query(MessageTreeState).filter(MessageTreeState.message_tree_id == message_tree_id).one_or_none()
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/orm/query.py", line 2849, in one_or_none
    return self._iter().one_or_none()
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/orm/query.py", line 2907, in _iter
    result = self.session.execute(
  File "/usr/local/lib/python3.10/site-packages/sqlmodel/orm/session.py", line 101, in execute
    return super().execute(  # type: ignore
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1660, in execute
    ) = compile_state_cls.orm_pre_session_exec(
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/orm/context.py", line 312, in orm_pre_session_exec
    session._autoflush()
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2257, in _autoflush
    util.raise_(e, with_traceback=sys.exc_info()[2])
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
    raise exception
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2246, in _autoflush
    self.flush()
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 3386, in flush
    self._flush(objects)
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 3525, in _flush
    with util.safe_reraise():
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
    raise exception
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 3486, in _flush
    flush_context.execute()
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/orm/unitofwork.py", line 456, in execute
    rec.execute(self)
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/orm/unitofwork.py", line 630, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/orm/persistence.py", line 245, in save_obj
    _emit_insert_statements(
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/orm/persistence.py", line 1097, in _emit_insert_statements
    c = connection._execute_20(
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1705, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 333, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1572, in _execute_clauseelement
    ret = self._execute_context(
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1943, in _execute_context
    self._handle_dbapi_exception(
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2124, in _handle_dbapi_exception
    util.raise_(
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
    raise exception
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)
(psycopg2.errors.NotNullViolation) null value in column "lang" of relation "message_tree_state" violates not-null constraint
DETAIL:  Failing row contains (cff4c829-c788-44a1-a20d-7451af932f9d, 0, 0, 0, backlog_ranking, f, export.json, null, null).

[SQL: INSERT INTO message_tree_state (message_tree_id, origin, won_prompt_lottery_date, lang, goal_tree_size, max_depth, max_children_count, state, active) VALUES (%(message_tree_id)s, %(origin)s, %(won_prompt_lottery_date)s, %(lang)s, %(goal_tree_size)s, %(max_depth)s, %(max_children_count)s, %(state)s, %(active)s)]
[parameters: {'message_tree_id': UUID('cff4c829-c788-44a1-a20d-7451af932f9d'), 'origin': 'export.json', 'won_prompt_lottery_date': None, 'lang': None, 'goal_tree_size': 0, 'max_depth': 0, 'max_children_count': 0, 'state': 'backlog_ranking', 'active': False}]
(Background on this error at: https://sqlalche.me/e/14/gkpj)
```

So, how can I use this script correctly?

**Comment by nero19960329** [comment]
The problem is:

Code around here imports the `MessageTreeState`, but without `lang`.

https://github.com/LAION-AI/Open-Assistant/blob/1f23005960d98fd0a00fe64d606a5b11da9093aa/backend/import.py#L87

While `lang` is a non-`nullable` attribute of `MessageTreeState`:

https://github.com/LAION-AI/Open-Assistant/blob/1f23005960d98fd0a00fe64d606a5b11da9093aa/backend/oasst_backend/models/message_tree_state.py#L89

Therefore the ORM insert transaction will not be successfully executed.

One of the solution is adding `lang` attribute when importing `MessageTreeState` with root_msg's `lang`.

**Comment by nero19960329** [comment]
Hope #1929 could fix it, I test it in my own data, it worked.
