### ISSUE TITLE
Can't use oasst-data

### ISSUE THREAD

**Issue by TheEighthDay** [LAION-AI/Open-Assistant#2772]
After `pip install -e .` [oasst-data](https://github.com/LAION-AI/Open-Assistant/tree/main/oasst-data)
When i try to
`from oasst_data import read_message_trees, visit_messages_depth_first, ExportMessageNode`

I get this:

```
Traceback (most recent call last):
  File "/Users/tiankaibin/Desktop/LLM/llm-sft/generate_instruction/open_data/oasst-data-script.py", line 1, in <module>
    from oasst_data import read_message_trees, visit_messages_depth_first, ExportMessageNode
  File "/Users/tiankaibin/Desktop/LLM/llm-sft/generate_instruction/open_data/oasst-data/oasst_data/__init__.py", line 1, in <module>
    from oasst_data.reader import read_message_list, read_message_tree_list, read_message_trees, read_messages
  File "/Users/tiankaibin/Desktop/LLM/llm-sft/generate_instruction/open_data/oasst-data/oasst_data/reader.py", line 8, in <module>
    from .schemas import ExportMessageNode, ExportMessageTree
  File "/Users/tiankaibin/Desktop/LLM/llm-sft/generate_instruction/open_data/oasst-data/oasst_data/schemas.py", line 9, in <module>
    class LabelAvgValue(BaseModel):
  File "pydantic/main.py", line 178, in pydantic.main.ModelMetaclass.__new__
  File "pydantic/typing.py", line 399, in pydantic.typing.resolve_annotations
    should not be set on instances of that class. Usage::
  File "/usr/local/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/typing.py", line 292, in _eval_type
    return t._evaluate(globalns, localns, recursive_guard)
  File "/usr/local/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/typing.py", line 554, in _evaluate
    eval(self.__forward_code__, globalns, localns),
  File "<string>", line 1, in <module>
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'
```

**Comment by olliestanley** [comment]
You need to update your Python version to 3.10
