### ISSUE TITLE
Application error: a client-side exception has occurred (see the browser console for more information). Please help. I got this error on my chrome, Brave and edge browser.

### ISSUE THREAD

**Issue by brokenduck2** [LAION-AI/Open-Assistant#3030]
Failed to load resource: the server responded with a status of 422 ()
framework-2fe4cb6473b20297.js:9  Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Bloc%2C%20msg%2C%20type%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at l0 (framework-2fe4cb6473b20297.js:9:54223)
    at d (framework-2fe4cb6473b20297.js:9:56028)
    at framework-2fe4cb6473b20297.js:9:58168
    at o (framework-2fe4cb6473b20297.js:9:58459)
    at uo (framework-2fe4cb6473b20297.js:9:71134)
    at i (framework-2fe4cb6473b20297.js:9:121296)
    at oD (framework-2fe4cb6473b20297.js:9:99116)
    at framework-2fe4cb6473b20297.js:9:98983
    at oO (framework-2fe4cb6473b20297.js:9:98990)
    at oE (framework-2fe4cb6473b20297.js:9:95742)
a9 @ framework-2fe4cb6473b20297.js:9
main-5263bf0fcb6e6b4e.js:1  Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Bloc%2C%20msg%2C%20type%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at l0 (framework-2fe4cb6473b20297.js:9:54223)
    at d (framework-2fe4cb6473b20297.js:9:56028)
    at framework-2fe4cb6473b20297.js:9:58168
    at o (framework-2fe4cb6473b20297.js:9:58459)
    at uo (framework-2fe4cb6473b20297.js:9:71134)
    at i (framework-2fe4cb6473b20297.js:9:121296)
    at oD (framework-2fe4cb6473b20297.js:9:99116)
    at framework-2fe4cb6473b20297.js:9:98983
    at oO (framework-2fe4cb6473b20297.js:9:98990)
    at oE (framework-2fe4cb6473b20297.js:9:95742)
X @ main-5263bf0fcb6e6b4e.js:1
main-5263bf0fcb6e6b4e.js:1  A client-side exception has occurred, see here for more info: https://nextjs.org/docs/messages/client-side-exception-occurred
X @ main-5263bf0fcb6e6b4e.js:1
/api/chat/assistant_message:1 
        
        
        Failed to load resource: the server responded with a status of 422 ()
framework-2fe4cb6473b20297.js:9  Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Bloc%2C%20msg%2C%20type%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at l0 (framework-2fe4cb6473b20297.js:9:54223)
    at d (framework-2fe4cb6473b20297.js:9:56028)
    at framework-2fe4cb6473b20297.js:9:58168
    at o (framework-2fe4cb6473b20297.js:9:58459)
    at uo (framework-2fe4cb6473b20297.js:9:71134)
    at i (framework-2fe4cb6473b20297.js:9:121296)
    at oD (framework-2fe4cb6473b20297.js:9:99116)
    at framework-2fe4cb6473b20297.js:9:98983
    at oO (framework-2fe4cb6473b20297.js:9:98990)
    at oE (framework-2fe4cb6473b20297.js:9:95742)
a9 @ framework-2fe4cb6473b20297.js:9
main-5263bf0fcb6e6b4e.js:1  Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Bloc%2C%20msg%2C%20type%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at l0 (framework-2fe4cb6473b20297.js:9:54223)
    at d (framework-2fe4cb6473b20297.js:9:56028)
    at framework-2fe4cb6473b20297.js:9:58168
    at o (framework-2fe4cb6473b20297.js:9:58459)
    at uo (framework-2fe4cb6473b20297.js:9:71134)
    at i (framework-2fe4cb6473b20297.js:9:121296)
    at oD (framework-2fe4cb6473b20297.js:9:99116)
    at framework-2fe4cb6473b20297.js:9:98983
    at oO (framework-2fe4cb6473b20297.js:9:98990)
    at oE (framework-2fe4cb6473b20297.js:9:95742)
X @ main-5263bf0fcb6e6b4e.js:1
main-5263bf0fcb6e6b4e.js:1  A client-side exception has occurred, see here for more info: https://nextjs.org/docs/messages/client-side-exception-occurred

**Comment by olliestanley** [comment]
Was this a one-off error or do you get it regularly?

**Comment by maxiy01** [comment]
Getting this regularly too. Can't open chat page both on PC (brave bowser) and on android (opera).  Console output on pc looks like this:
```
framework-ce84985cd166733a.js:9 TypeError: r.at is not a function
    at s (_app-a255f8fe53177b14.js:305)
    at l (_app-a255f8fe53177b14.js:305)
    at ab (framework-ce84985cd166733a.js:9)
    at i (framework-ce84985cd166733a.js:9)
    at oO (framework-ce84985cd166733a.js:9)
    at framework-ce84985cd166733a.js:9
    at oF (framework-ce84985cd166733a.js:9)
    at ox (framework-ce84985cd166733a.js:9)
    at oS (framework-ce84985cd166733a.js:9)
    at x (framework-ce84985cd166733a.js:33)

main-70e4b9535b9ffc41.js:1 TypeError: r.at is not a function
    at s (_app-a255f8fe53177b14.js:305)
    at l (_app-a255f8fe53177b14.js:305)
    at ab (framework-ce84985cd166733a.js:9)
    at i (framework-ce84985cd166733a.js:9)
    at oO (framework-ce84985cd166733a.js:9)
    at framework-ce84985cd166733a.js:9
    at oF (framework-ce84985cd166733a.js:9)
    at ox (framework-ce84985cd166733a.js:9)
    at oS (framework-ce84985cd166733a.js:9)
    at x (framework-ce84985cd166733a.js:33)

main-70e4b9535b9ffc41.js:1 A client-side exception has occurred, see here for more info: https://nextjs.org/docs/messages/client-side-exception-occurred

Error: Minified React error #423; visit https://reactjs.org/docs/error-decoder.html?invariant=423 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at i (framework-ce84985cd166733a.js:9)
    at oO (framework-ce84985cd166733a.js:9)
    at framework-ce84985cd166733a.js:9
    at oF (framework-ce84985cd166733a.js:9)
    at ox (framework-ce84985cd166733a.js:9)
    at oS (framework-ce84985cd166733a.js:9)
    at x (framework-ce84985cd166733a.js:33)
    at MessagePort.T (framework-ce84985cd166733a.js:33)
    
Error rendering page:  Error: Cancel rendering route
    at c (main-70e4b9535b9ffc41.js:1)
    at main-70e4b9535b9ffc41.js:1
    at new Promise (<anonymous>)
    at ea (main-70e4b9535b9ffc41.js:1)
    at main-70e4b9535b9ffc41.js:1
```
![open-assistant-broken-chat](https://github.com/LAION-AI/Open-Assistant/assets/22634701/5e583a64-03c5-4032-a7ed-7eec97ff16ff)
