### ISSUE TITLE
 RuntimeError: can't start new thread

### ISSUE THREAD

**Issue by 283859691** [LAION-AI/Open-Assistant#3476]
> [inference-worker  4/10] RUN conda create -n worker python=3.10 -y:
#0 0.780 Retrieving notices: ...working... failed
#0 1.227 
#0 1.227 # >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<
#0 1.227 
#0 1.227     Traceback (most recent call last):
#0 1.227       File "/opt/miniconda/lib/python3.10/site-packages/conda/exceptions.py", line 1124, in __call__
#0 1.227         return func(*args, **kwargs)
#0 1.227       File "/opt/miniconda/lib/python3.10/site-packages/conda/cli/main.py", line 69, in main_subshell
#0 1.227         exit_code = do_call(args, p)
#0 1.227       File "/opt/miniconda/lib/python3.10/site-packages/conda/cli/conda_argparse.py", line 91, in do_call
#0 1.227         return getattr(module, func_name)(args, parser)
#0 1.227       File "/opt/miniconda/lib/python3.10/site-packages/conda/notices/core.py", line 98, in wrapper
#0 1.227         channel_notice_set = retrieve_notices(
#0 1.227       File "/opt/miniconda/lib/python3.10/site-packages/conda/notices/core.py", line 39, in retrieve_notices
#0 1.227         channel_notice_responses = fetch.get_notice_responses(channel_name_urls, silent=silent)
#0 1.227       File "/opt/miniconda/lib/python3.10/site-packages/conda/notices/fetch.py", line 41, in get_notice_responses
#0 1.227         for chn_info in executor.map(
#0 1.227       File "/opt/miniconda/lib/python3.10/concurrent/futures/_base.py", line 610, in map
#0 1.227         fs = [self.submit(fn, *args) for args in zip(*iterables)]
#0 1.227       File "/opt/miniconda/lib/python3.10/concurrent/futures/_base.py", line 610, in <listcomp>
#0 1.227         fs = [self.submit(fn, *args) for args in zip(*iterables)]
#0 1.227       File "/opt/miniconda/lib/python3.10/concurrent/futures/thread.py", line 176, in submit
#0 1.227         self._adjust_thread_count()
#0 1.227       File "/opt/miniconda/lib/python3.10/concurrent/futures/thread.py", line 199, in _adjust_thread_count
#0 1.227         t.start()
#0 1.227       File "/opt/miniconda/lib/python3.10/threading.py", line 935, in start
#0 1.227         _start_new_thread(self._bootstrap, ())
#0 1.227     RuntimeError: can't start new thread
#0 1.227 
#0 1.227 `$ /opt/miniconda/bin/conda create -n worker python=3.10 -y`
#0 1.227 
#0 1.227   environment variables:
#0 1.227         APP_RELATIVE_PATH=inference/worker
#0 1.227                  CIO_TEST=<not set>
#0 1.227         CONDA_DEFAULT_ENV=text-generation
#0 1.227                CONDA_ROOT=/opt/miniconda
#0 1.227            CURL_CA_BUNDLE=<not set>
#0 1.227           LD_LIBRARY_PATH=/opt/miniconda/envs/text-generation/lib:/usr/local/cuda/lib64:/usr/loc
#0 1.227                           al/cuda/extras/CUPTI/lib64:/usr/local/nvidia/lib:/usr/local/nvidia/lib
#0 1.227                           64
#0 1.227                LD_PRELOAD=<not set>
#0 1.227              LIBRARY_PATH=/usr/local/cuda/lib64/stubs
#0 1.227                      PATH=/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/b
#0 1.227                           in:/usr/sbin:/usr/bin:/sbin:/bin:/opt/miniconda/envs/text-
#0 1.227                           generation/bin:/opt/miniconda/bin:/usr/local/cuda/bin
#0 1.227        REQUESTS_CA_BUNDLE=<not set>
#0 1.227             SSL_CERT_FILE=<not set>
#0 1.227 
#0 1.227      active environment : None
#0 1.227        user config file : /root/.condarc
#0 1.227  populated config files : 
#0 1.227           conda version : 23.1.0
#0 1.227     conda-build version : not installed
#0 1.227          python version : 3.10.9.final.0
#0 1.227        virtual packages : __archspec=1=x86_64
#0 1.227                           __glibc=2.35=0
#0 1.227                           __linux=3.10.0=0
#0 1.227                           __unix=0=0
#0 1.227        base environment : /opt/miniconda  (writable)
#0 1.227       conda av data dir : /opt/miniconda/etc/conda
#0 1.227   conda av metadata url : None
#0 1.227            channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
#0 1.227                           https://repo.anaconda.com/pkgs/main/noarch
#0 1.227                           https://repo.anaconda.com/pkgs/r/linux-64
#0 1.227                           https://repo.anaconda.com/pkgs/r/noarch
#0 1.227           package cache : /opt/miniconda/pkgs
#0 1.227                           /root/.conda/pkgs
#0 1.227        envs directories : /opt/miniconda/envs
#0 1.227                           /root/.conda/envs
#0 1.227                platform : linux-64
#0 1.227              user-agent : conda/23.1.0 requests/2.28.1 CPython/3.10.9 Linux/3.10.0-1160.83.1.el7.x86_64 ubuntu/22.04.1 glibc/2.35
#0 1.227                 UID:GID : 0:0
#0 1.227              netrc file : None
#0 1.227            offline mode : False
#0 1.227 
#0 1.227 
#0 1.227 An unexpected error has occurred. Conda has prepared the above report.
#0 1.227 
#0 3.564 Upload successful.
------
failed to solve: executor failed running [/bin/sh -c conda create -n worker python=3.10 -y]: exit code: 1

command: docker-compose   --profile inference  --profile ci   up --build  -d

**Comment by 283859691** [comment]
ulimit  -a
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 63443
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 655350
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 63443
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited
