### ISSUE TITLE
Chat error: "Cannot read properties of undefined (reading 'children')"

### ISSUE THREAD

**Issue by maxiy01** [LAION-AI/Open-Assistant#3478]
When I use chat (web version), sometimes I get "Application error: a client-side exception has occurred (see the browser console for more information).". This sometimes happens when assistant generate response or when I press left/right buttons (the ones under my request, which has been edited) to "switch to different branch" (I don't know how to properly call it).

Browser console output:
```
TypeError: Cannot read properties of undefined (reading 'children')
    at tb ([id]-52c36ab214538aed.js:1:25941)
    at ab (framework-ce84985cd166733a.js:9:60917)
    at ud (framework-ce84985cd166733a.js:9:72803)
    at i (framework-ce84985cd166733a.js:9:120372)
    at oO (framework-ce84985cd166733a.js:9:99114)
    at framework-ce84985cd166733a.js:9:98981
    at oF (framework-ce84985cd166733a.js:9:98988)
    at ox (framework-ce84985cd166733a.js:9:95740)
    at oC (framework-ce84985cd166733a.js:9:96129)
    at r4 (framework-ce84985cd166733a.js:9:44778)
J
```

**Comment by notmd** [comment]
cc @someone13574

**Comment by myname1111** [comment]
I can confirm that this happens to me as well. Worse, it sometimes always happens on certain branches forcing me to completely abandon the branch
