### ISSUE TITLE
psycopg2.errors.SerializationFailure: could not serialize access due to concurrent delete

### ISSUE THREAD

**Issue by Zjk1021** [LAION-AI/Open-Assistant#3590]
```sh
2023-07-21 20:08:16.451 | ERROR    | main:update_leader_board_month:274 - Error during user states update (monthly)
Traceback (most recent call last):

  File "/home/lthpc/.conda/envs/oassistant/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
    self.dialect.do_execute(
    │    │       └ <function DefaultDialect.do_execute at 0x7fb0fae608b0>
    │    └ <sqlalchemy.dialects.postgresql.psycopg2.PGDialect_psycopg2 object at 0x7fb0f92b47f0>
    └ <sqlalchemy.future.engine.Connection object at 0x7faf907cdcf0>
  File "/home/lthpc/.conda/envs/oassistant/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
    │      │       │          └ {'time_frame_1': 'month'}
    │      │       └ 'DELETE FROM user_stats WHERE user_stats.time_frame = %(time_frame_1)s'
    │      └ <method 'execute' of 'psycopg2.extensions.cursor' objects>
    └ <cursor object at 0x7fafb00be7a0; closed: -1>

psycopg2.errors.SerializationFailure: could not serialize access due to concurrent delete

```

```python
    if not (args.print_openapi_schema or args.retry_scoring):
        uvicorn.run(app="main:app", host=args.host, port=int(args.port), workers=8)
```

**Comment by andreaskoepf** [comment]
I am closing this issue since it only contains an error message without further context.
