### ISSUE TITLE
Trouble getting backend dev up and running.

### ISSUE THREAD

**Issue by andrewm4894** [LAION-AI/Open-Assistant#597]
I am trying to follow steps here: https://github.com/LAION-AI/Open-Assistant/tree/main/backend#backend-development-setup

docker compose stuff looks good. i did the pip install stuff but when i run the script i get this: 

```bash
(venv) ➜  backend-development git:(backend-dev) bash run-local.sh
~/repos/Open-Assistant/backend ~/repos/Open-Assistant/scripts/backend-development
INFO:     Will watch for changes in these directories: ['/root/repos/Open-Assistant/backend']
INFO:     Uvicorn running on http://0.0.0.0:8080 (Press CTRL+C to quit)
INFO:     Started reloader process [6425] using StatReload
Process SpawnProcess-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/root/repos/Open-Assistant/venv/lib/python3.8/site-packages/uvicorn/_subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "/root/repos/Open-Assistant/venv/lib/python3.8/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/root/repos/Open-Assistant/venv/lib/python3.8/site-packages/uvicorn/server.py", line 67, in serve
    config.load()
  File "/root/repos/Open-Assistant/venv/lib/python3.8/site-packages/uvicorn/config.py", line 477, in load
    self.loaded_app = import_from_string(self.app)
  File "/root/repos/Open-Assistant/venv/lib/python3.8/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/root/repos/Open-Assistant/backend/./main.py", line 13, in <module>
    from oasst_backend.api.deps import get_dummy_api_client
  File "/root/repos/Open-Assistant/backend/./oasst_backend/api/deps.py", line 12, in <module>
    from oasst_backend.models import ApiClient
  File "/root/repos/Open-Assistant/backend/./oasst_backend/models/__init__.py", line 2, in <module>
    from .journal import Journal, JournalIntegration
  File "/root/repos/Open-Assistant/backend/./oasst_backend/models/journal.py", line 9, in <module>
    from .payload_column_type import PayloadContainer, payload_column_type
  File "/root/repos/Open-Assistant/backend/./oasst_backend/models/payload_column_type.py", line 21, in <module>
    class PayloadContainer(BaseModel):
  File "/root/repos/Open-Assistant/backend/./oasst_backend/models/payload_column_type.py", line 36, in PayloadContainer
    def check_payload(cls, v: BaseModel, values: dict[str, Any]) -> BaseModel:
TypeError: 'type' object is not subscriptable
```

![image](https://user-images.githubusercontent.com/2178292/211593170-6d862103-7657-48d7-87bd-687f38d6ab99.png)

```bash
(venv) ➜  Open-Assistant git:(backend-dev) pip freeze
aiohttp==3.8.3
aiosignal==1.3.1
alembic==1.8.1
anyio==3.6.2
async-timeout==4.0.2
attrs==22.2.0
charset-normalizer==2.1.1
click==8.1.3
fastapi==0.88.0
fastapi-limiter==0.1.5
frozenlist==1.3.3
greenlet==2.0.1
h11==0.14.0
idna==3.4
importlib-metadata==6.0.0
importlib-resources==5.10.2
loguru==0.6.0
Mako==1.2.4
MarkupSafe==2.1.1
multidict==6.0.4
numpy==1.22.4
-e git+https://github.com/andrewm4894/Open-Assistant.git@f1ea4ec1ddf4418a30804620aeee7ff433cee82c#egg=oasst_shared&subdirectory=oasst-shared
psycopg2-binary==2.9.5
pydantic==1.9.1
python-dotenv==0.21.0
redis==4.4.1
scipy==1.8.1
sniffio==1.3.0
SQLAlchemy==1.4.41
sqlalchemy2-stubs==0.0.2a31
sqlmodel==0.0.8
starlette==0.22.0
typing-extensions==4.4.0
uvicorn==0.20.0
yarl==1.8.2
zipp==3.11.0

```

I am using wsl in windows. Will dig a bit more myself but just wanted to make issue in case is an obvious one to someone else.

**Comment by olliestanley** [comment]
Looks like your Python is 3.8? I think it needs to be 3.10.8

**Comment by andrewm4894** [comment]
> Looks like your Python is 3.8? I think it needs to be 3.10.8

Oh cool thanks, will try that

**Comment by Nil-Andreu** [comment]
Yes, you have the supported python version in `.python_version` file, which is the one mentioned earlier. Do you need help on setting that python version in your computer?

**Comment by yk** [comment]
you can use pyenv, which will automatically pick up on `.python-version` files, and it has shell shims that make sure you use the correct one

**Comment by andrewm4894** [comment]
yes - have been fighting with pyenv and windows and bash inside of windows and wsl2 gave up and used a backend based devcontainer and was able to get it working in there. 

mainly just wanted to get backend dev running to grap the openapi.json from the local fastapi to see if could be a sort of basis for some BE api docs people could easily scan without having to set up a backend dev env. 

https://github.com/LAION-AI/Open-Assistant/pull/608

will close this for now and continue my local windows battle some other day - github codespaces enabling me to do most stuff in there instead for now.
